---
title: "Developing Data Products Week 2 Assignment"
author: "Keval Bhavsar"
date: "08/07/2020"
output: html_document
---

## Instructions

Create a web page using R Markdown that features a map created with Leaflet.

Host your webpage on either GitHub Pages, RPubs, or NeoCities.

Your webpage must contain the date that you created the document, and it must contain a map created with Leaflet.

## Review criteria

The rubric contains the following two questions:

Does the web page feature a date and is this date less than two months before the date that you’re grading this assignment?
Does the web page feature an interactive map that appears to have been created with Leaflet?

## Submission

Here is the Gandhi Ashram, Kankaria Lake, Sidi Saiyad Mosque, Sabarmati Riverfront, Jama MAsjid, and The Adalaj Stepwell, which are the popular visiting places in Ahmedabad.
```{R}
library(knitr)
library(leaflet)
library(dplyr)
```
```{R}
m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lat=23.0608, lng=72.5809, popup="Gandhi Ashram, Ahmedabad") %>%
  addMarkers(lat=23.0063, lng=72.6026, popup="Kankaria Lake, Ahmedabad") %>%
  addMarkers(lat=23.0270, lng=72.5810, popup="Sidi Saiyyed Mosque, Ahmedabad") %>%
  addMarkers(lat=23.0235, lng=72.5766, popup="Sabarmati Riverfront, Ahmedabad") %>%
  addMarkers(lat=23.0239, lng=72.5871, popup="Jama Masjid, Ahmedabad") %>%
  addMarkers(lat=23.1667, lng=72.5801, popup="The Adalaj Stepwell, Ahmedabad") %>%
  setView (lat=23.0608, lng=72.5809, zoom=16) 
m  # Print the map
```

## Mapping Clusters

When you zoom in to each cluster, the cluster will seperate until you see the individual Markers!!

```{R, message = FALSE}
df <- data.frame(lat=runif(500, min=23.00, max = 23.10),
                 lng=runif(500, min=72.50, max = 72.60))
```
```{R}
df %>%
  leaflet() %>%
  addTiles() %>%  
  addMarkers(clusterOptions = markerClusterOptions())
```